apiVersion: v1
kind: Secret
metadata:
  name: django-env
type: Opaque
stringData:
  DJANGO_SECRET_KEY: 'your_secret_key'
  DATABASE_NAME: 'zentric_db'
  DATABASE_USER: 'postgres'
  DATABASE_PASSWORD: 'postgres'
  DATABASE_HOST: 'postgresql-service'
  DATABASE_PORT: '5432'
