apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
spec:
  type: LoadBalancer  # Exponer el servicio
  selector:
    app: postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
