# Generated by Django 5.0.7 on 2024-08-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Ingreso'), ('OUT', 'Salida')], max_length=3),
        ),
    ]
