# Generated by Django 5.0.7 on 2024-08-02 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0002_alter_inventorytransaction_transaction_type'),
        ('products', '0007_product_reorder_level_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inventory_transactions', to='products.product'),
        ),
    ]
