# Generated by Django 5.0.7 on 2024-07-30 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_publish_product', 'Can publish product'), ('can_review_product', 'Can review product')]},
        ),
    ]
