# Generated by Django 5.0.7 on 2024-08-01 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_reorder_level_product_stock_product_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
