# Generated by Django 5.0.7 on 2024-08-02 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_reorder_level_alter_product_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('view_product2', 'Can view product'), ('edit_product2', 'Can edit product')]},
        ),
    ]
